# Generated by Django 6.0.2 on 2026-03-02 00:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('waist_circumference_cm', models.FloatField(blank=True, null=True)),
                ('emotional_stress', models.FloatField(blank=True, null=True)),
                ('alcohol_units_per_week', models.FloatField(blank=True, null=True)),
                ('daily_calories_kcal', models.FloatField(blank=True, null=True)),
                ('max_push_ups', models.FloatField(blank=True, null=True)),
                ('max_pull_ups', models.FloatField(blank=True, null=True)),
                ('run_1km_min', models.FloatField(blank=True, null=True)),
                ('run_100m_sec', models.FloatField(blank=True, null=True)),
                ('cooper_test_km', models.FloatField(blank=True, null=True)),
                ('burpees_3min', models.FloatField(blank=True, null=True)),
                ('push_ups_1min', models.FloatField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('resting_heart_rate_bpm', models.FloatField(blank=True, null=True)),
                ('systolic_blood_pressure_mmhg', models.FloatField(blank=True, null=True)),
                ('mitochondria_placeholder', models.FloatField(blank=True, null=True)),
                ('testosterone_ng_dl', models.FloatField(blank=True, null=True)),
                ('cortisol_ug_dl', models.FloatField(blank=True, null=True)),
                ('hemoglobin_g_dl', models.FloatField(blank=True, null=True)),
                ('crp_mg_l', models.FloatField(blank=True, null=True)),
                ('hrv', models.FloatField(blank=True, null=True)),
                ('prediction', models.JSONField(blank=True, null=True)),
                ('weekly_plan', models.JSONField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_history', to='fitness.userprofile')),
            ],
            options={
                'verbose_name': 'User Data Record',
                'verbose_name_plural': 'User Data History',
                'ordering': ['-timestamp'],
            },
        ),
    ]
