# Generated by Django 6.0.2 on 2026-03-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='profile',
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
